base_url = "https://djanda97.pages.dev"

theme = "terminimal"

title = "/home/djanda97"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]
accent_color = "orange"
logo_text = "/home/djanda97"
page_titles = "combined"

menu_items = [
    { name = "github", url = "https://github.com/djanda97", newtab = true },
]
