base_url = "https://djanda97.pages.dev"

theme = "terminimal"

title = "~djanda97"

compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[extra]
accent_color = "orange"
logo_text = "~djanda97"
page_titles = "combined"

menu_items = [
    { name = "github", url = "https://github.com/djanda97", newtab = true },
    { name = "linkedin", url = "https://www.linkedin.com/in/david-janda/", newtab = true },
    { name = "goodreads", url = "https://www.goodreads.com/user/show/165326841-david-janda", newtab = true },
]
